name: Build and deploy Node.js app to Azure Web App - my-product-catalogue-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ------------------------------
  # Backend Build Job
  # ------------------------------
  backend-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: |
          cd product-catalogue-backend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for backend deployment
        run: |
          cd product-catalogue-backend
          zip -r ../backend-release.zip .

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend-release.zip

  # ------------------------------
  # Backend Deployment Job
  # ------------------------------
  backend-deploy:
    runs-on: ubuntu-latest
    needs: backend-build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Unzip backend artifact for deployment
        run: unzip backend-release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Backend to Azure Web App
        id: deploy-backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-product-catalogue-app'
          slot-name: 'Production'
          package: .

  # ------------------------------
  # Frontend Build Job
  # ------------------------------
  frontend-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install frontend dependencies and build
        run: |
          cd product-catalogue-frontend
          npm install
          npm run build

      - name: Zip artifact for frontend deployment
        run: |
          cd product-catalogue-frontend/build
          zip -r ../../frontend-release.zip .

      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend-release.zip

  # ------------------------------
  # Frontend Deployment Job
  # ------------------------------
  frontend-deploy:
    runs-on: ubuntu-latest
    needs: frontend-build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-app

      - name: Unzip frontend artifact for deployment
        run: unzip frontend-release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Frontend to Azure Static Web App
        id: deploy-frontend
        uses: azure/static-web-apps-deploy@v1
        with:
          app_location: '/product-catalogue-frontend/build'
          output_location: ''
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}






# name: Build and deploy Node.js app to Azure Web App - my-product-catalogue-app

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   backend-build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read # This is required for actions/checkout

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '22.x'

#       - name: Install backend dependencies
#         run: |
#           cd product-catalogue-backend
#           npm install
#           npm run build --if-present
#           npm run test --if-present

#       - name: Zip artifact for backend deployment
#         run: |
#           cd product-catalogue-backend
#           zip -r ../backend-release.zip .

#       - name: Upload backend artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: backend-app
#           path: backend-release.zip

#   backend-deploy:
#     runs-on: ubuntu-latest
#     needs: backend-build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#     permissions:
#       id-token: write # This is required for requesting the JWT
#       contents: read # This is required for actions/checkout

#     steps:
#       - name: Download backend artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: backend-app

#       - name: Unzip backend artifact for deployment
#         run: unzip backend-release.zip
      
# - name: Azure Login
#   uses: azure/login@v2
#   with:
#     client-id: ${{ secrets.AZURE_CLIENT_ID }}
#     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#     enable-AzPSSession: true


#       - name: 'Deploy Backend to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'my-product-catalogue-backend'
#           slot-name: 'Production'
#           package: .

# # -----------------------------------------------------------

# # 2. **Frontend Deployment**  
# # Add a separate job for deploying the frontend React app:

#   frontend-build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '22.x'

#       - name: Install frontend dependencies and build
#         run: |
#           cd product-catalogue-frontend
#           npm install
#           npm run build

#       - name: Zip artifact for frontend deployment
#         run: |
#           cd product-catalogue-frontend/build
#           zip -r ../../frontend-release.zip .

#       - name: Upload frontend artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: frontend-app
#           path: frontend-release.zip

#   frontend-deploy:
#     runs-on: ubuntu-latest
#     needs: frontend-build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Download frontend artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: frontend-app

#       - name: Unzip frontend artifact for deployment
#         run: unzip frontend-release.zip

# - name: Azure Login
#   uses: azure/login@v2
#   with:
#     client-id: ${{ secrets.AZURE_CLIENT_ID }}
#     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#     enable-AzPSSession: true



#       - name: 'Deploy Frontend to Azure Static Web App'
#         id: deploy-to-webapp
#         uses: azure/static-web-apps-deploy@v1
#         with:
#           app_location: '/product-catalogue-frontend/build'
#           output_location: ''
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}



















# # # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # # More GitHub Actions for Azure: https://github.com/Azure/actions

# # name: Build and deploy Node.js app to Azure Web App - my-product-catalogue-app

# # on:
# #   push:
# #     branches:
# #       - main
# #   workflow_dispatch:

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest
# #     permissions:
# #       contents: read #This is required for actions/checkout

# #     steps:
# #       - uses: actions/checkout@v4

# #       - name: Set up Node.js version
# #         uses: actions/setup-node@v3
# #         with:
# #           node-version: '22.x'

# #       - name: npm install, build, and test
# #         run: |
# #           npm install
# #           npm run build --if-present
# #           npm run test --if-present

# #       - name: Zip artifact for deployment
# #         run: zip release.zip ./* -r

# #       - name: Upload artifact for deployment job
# #         uses: actions/upload-artifact@v4
# #         with:
# #           name: node-app
# #           path: release.zip

# #   deploy:
# #     runs-on: ubuntu-latest
# #     needs: build
# #     environment:
# #       name: 'Production'
# #       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
# #     permissions:
# #       id-token: write #This is required for requesting the JWT
# #       contents: read #This is required for actions/checkout

# #     steps:
# #       - name: Download artifact from build job
# #         uses: actions/download-artifact@v4
# #         with:
# #           name: node-app

# #       - name: Unzip artifact for deployment
# #         run: unzip release.zip
      
# #       - name: Login to Azure
# #         uses: azure/login@v2
# #         with:
# #           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FD5CA8FD9BA84FB4BE27D47D5A8759C2 }}
# #           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA158C733FF7404594E7F531EF939AF1 }}
# #           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AFD76BF30224197A3A533AAD14F7823 }}

# #       - name: 'Deploy to Azure Web App'
# #         id: deploy-to-webapp
# #         uses: azure/webapps-deploy@v3
# #         with:
# #           app-name: 'my-product-catalogue-app'
# #           slot-name: 'Production'
# #           package: .
          
